//! Rust -> TypeScript codegen across the registry seam (spec §9,
//! "adoption-critical").
//!
//! The registry is defined once in Rust; this crate emits the matching
//! TypeScript module so "add an action" is one Rust edit and the frontend is
//! type-safe for free. Apps call [`typescript_module`] from a build script or
//! a small `cargo run --bin codegen` target and write the output into their
//! frontend source tree.
//!
//! Emitted per registry:
//!
//! - `ActionId` / `BlockType` string-literal unions (the closed vocabularies)
//! - one params interface per action (context- and utterance-sourced both:
//!   the frontend receives *filled* params in proposals)
//! - one slots interface per block type
//! - `ActionParamsMap` / `BlockSlotsMap` lookup interfaces keyed by ID
//! - an `ACTIONS` metadata const (`blockType`, `mutates`) for the block
//!   router and UI affordances

use std::fmt::Write as _;

use cleverhans_core::registry::{ActionDef, BlockDef, ParamSource, ValueType};

/// Header prepended to every generated module.
const HEADER: &str = "\
// AUTO-GENERATED by cleverhans-codegen — do not edit.
// Regenerate from the Rust action registry (spec §9: one source, three consumers).
";

/// Converts an inert key like `transaction.coBuyer.remove` into a TypeScript
/// identifier prefix like `TransactionCoBuyerRemove`.
///
/// Splits on any non-alphanumeric character and on lowercase→uppercase
/// boundaries, then PascalCases the segments — the ID itself stays an opaque
/// string everywhere; this name is presentation only.
#[must_use]
pub fn pascal_ident(id: &str) -> String {
    id.split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|segment| !segment.is_empty())
        .flat_map(split_camel_boundaries)
        .map(|word| {
            let mut chars = word.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_ascii_uppercase().to_string() + &chars.as_str().to_ascii_lowercase()
            })
        })
        .collect()
}

fn split_camel_boundaries(segment: &str) -> Vec<&str> {
    let mut words = Vec::new();
    let mut start = 0;
    for (index, c) in segment.char_indices().skip(1) {
        let prev_is_lower = segment[..index]
            .chars()
            .next_back()
            .is_some_and(|p| p.is_ascii_lowercase());
        if c.is_ascii_uppercase() && prev_is_lower {
            words.push(&segment[start..index]);
            start = index;
        }
    }
    words.push(&segment[start..]);
    words
}

fn ts_type(ty: &ValueType) -> String {
    match ty {
        ValueType::String => "string".to_owned(),
        ValueType::Integer | ValueType::Number => "number".to_owned(),
        ValueType::Boolean => "boolean".to_owned(),
        ValueType::StringEnum(allowed) => allowed
            .iter()
            .map(|value| format!("\"{}\"", value.replace('"', "\\\"")))
            .collect::<Vec<_>>()
            .join(" | "),
        ValueType::Json => "unknown".to_owned(),
    }
}

fn union_of(ids: impl Iterator<Item = String>) -> String {
    let variants: Vec<_> = ids.map(|id| format!("\"{id}\"")).collect();
    if variants.is_empty() {
        "never".to_owned()
    } else {
        variants.join(" | ")
    }
}

fn push_params_interface(out: &mut String, action: &ActionDef) {
    let name = pascal_ident(&action.id);
    let _ = writeln!(out, "/** Filled params of `{}`. */", action.id);
    let _ = writeln!(out, "export interface {name}Params {{");
    for param in &action.params {
        let source = match param.source {
            ParamSource::Context => "context",
            ParamSource::Utterance => "utterance",
        };
        let optional = if param.required { "" } else { "?" };
        let _ = writeln!(
            out,
            "  /** source: {source} */\n  {}{optional}: {};",
            param.name,
            ts_type(&param.ty)
        );
    }
    let _ = writeln!(out, "}}");
}

fn push_slots_interface(out: &mut String, block: &BlockDef) {
    let name = pascal_ident(&block.block_type);
    let _ = writeln!(out, "/** Slots of block type `{}`. */", block.block_type);
    let _ = writeln!(out, "export interface {name}Slots {{");
    for slot in &block.slots {
        let optional = if slot.required { "" } else { "?" };
        let _ = writeln!(out, "  {}{optional}: {};", slot.name, ts_type(&slot.ty));
    }
    let _ = writeln!(out, "}}");
}

/// Renders the full generated TypeScript module for a registry's definitions.
///
/// Definitions are emitted in the given order; pass them straight from
/// `Registry::action_defs()` / `Registry::block_defs()` for deterministic
/// (ID-sorted) output.
#[must_use]
pub fn typescript_module<'a>(
    actions: impl IntoIterator<Item = &'a ActionDef>,
    blocks: impl IntoIterator<Item = &'a BlockDef>,
) -> String {
    let actions: Vec<_> = actions.into_iter().collect();
    let blocks: Vec<_> = blocks.into_iter().collect();
    let mut out = String::from(HEADER);

    let _ = writeln!(
        &mut out,
        "\nexport type ActionId = {};",
        union_of(actions.iter().map(|a| a.id.clone()))
    );
    let _ = writeln!(
        &mut out,
        "\nexport type BlockType = {};",
        union_of(blocks.iter().map(|b| b.block_type.clone()))
    );

    for block in &blocks {
        let _ = writeln!(&mut out);
        push_slots_interface(&mut out, block);
    }
    for action in &actions {
        let _ = writeln!(&mut out);
        push_params_interface(&mut out, action);
    }

    let _ = writeln!(&mut out, "\nexport interface BlockSlotsMap {{");
    for block in &blocks {
        let _ = writeln!(
            &mut out,
            "  \"{}\": {}Slots;",
            block.block_type,
            pascal_ident(&block.block_type)
        );
    }
    let _ = writeln!(&mut out, "}}");

    let _ = writeln!(&mut out, "\nexport interface ActionParamsMap {{");
    for action in &actions {
        let _ = writeln!(
            &mut out,
            "  \"{}\": {}Params;",
            action.id,
            pascal_ident(&action.id)
        );
    }
    let _ = writeln!(&mut out, "}}");

    let _ = writeln!(
        &mut out,
        "\nexport const ACTIONS: {{\n  [K in ActionId]: {{ blockType: BlockType; mutates: boolean }};\n}} = {{"
    );
    for action in &actions {
        let _ = writeln!(
            &mut out,
            "  \"{}\": {{ blockType: \"{}\", mutates: {} }},",
            action.id, action.block_type, action.mutates
        );
    }
    let _ = writeln!(&mut out, "}};");

    out
}

#[cfg(test)]
mod tests {
    use cleverhans_core::registry::{ParamSpec, SlotSpec};

    use super::*;

    fn remove_action() -> ActionDef {
        ActionDef {
            id: "transaction.coBuyer.remove".to_owned(),
            description: "Remove the co-buyer".to_owned(),
            params: vec![
                ParamSpec {
                    name: "transactionId".to_owned(),
                    description: String::new(),
                    ty: ValueType::String,
                    source: ParamSource::Context,
                    required: true,
                },
                ParamSpec {
                    name: "country".to_owned(),
                    description: "ISO code".to_owned(),
                    ty: ValueType::StringEnum(vec!["NO".to_owned(), "DK".to_owned()]),
                    source: ParamSource::Utterance,
                    required: false,
                },
            ],
            block_type: "confirm".to_owned(),
            mutates: true,
            authz_key: "tx".to_owned(),
        }
    }

    fn confirm_block() -> BlockDef {
        BlockDef {
            block_type: "confirm".to_owned(),
            slots: vec![
                SlotSpec {
                    name: "title".to_owned(),
                    ty: ValueType::String,
                    required: true,
                },
                SlotSpec {
                    name: "detail".to_owned(),
                    ty: ValueType::String,
                    required: false,
                },
            ],
        }
    }

    mod pascal_ident {
        use super::*;

        #[test]
        fn splits_dots_and_camel_case() {
            assert_eq!(
                pascal_ident("transaction.coBuyer.remove"),
                "TransactionCoBuyerRemove"
            );
        }

        #[test]
        fn handles_snake_and_kebab() {
            assert_eq!(
                pascal_ident("bulk_ops.delete-by-predicate"),
                "BulkOpsDeleteByPredicate"
            );
        }
    }

    mod typescript_module {
        use super::*;

        #[test]
        fn emits_action_id_union() {
            let module = typescript_module([&remove_action()], [&confirm_block()]);

            assert!(
                module.contains("export type ActionId = \"transaction.coBuyer.remove\";"),
                "missing union in:\n{module}"
            );
        }

        #[test]
        fn optional_param_gets_question_mark() {
            let module = typescript_module([&remove_action()], [&confirm_block()]);

            assert!(
                module.contains("country?: \"NO\" | \"DK\";"),
                "missing optional enum param in:\n{module}"
            );
        }

        #[test]
        fn required_context_param_is_plain_string() {
            let module = typescript_module([&remove_action()], [&confirm_block()]);

            assert!(
                module.contains("transactionId: string;"),
                "missing context param in:\n{module}"
            );
        }

        #[test]
        fn metadata_const_carries_block_type_and_mutates() {
            let module = typescript_module([&remove_action()], [&confirm_block()]);

            assert!(
                module.contains(
                    "\"transaction.coBuyer.remove\": { blockType: \"confirm\", mutates: true },"
                ),
                "missing metadata entry in:\n{module}"
            );
        }

        #[test]
        fn empty_registry_yields_never_unions() {
            let module = typescript_module([], []);

            assert!(
                module.contains("export type ActionId = never;"),
                "empty union should be never:\n{module}"
            );
        }

        #[test]
        fn slots_interface_matches_block_schema() {
            let module = typescript_module([&remove_action()], [&confirm_block()]);

            assert!(
                module.contains(
                    "export interface ConfirmSlots {\n  title: string;\n  detail?: string;\n}"
                ),
                "missing slots interface in:\n{module}"
            );
        }
    }
}
