//! Python emitter (3.11+, stdlib `typing` only).
//!
//! Mirrors the TypeScript module structurally: `Literal` unions for the
//! closed vocabularies, one `TypedDict` per action's params and per block's
//! slots (`NotRequired` for optional fields), and an `ACTIONS` metadata
//! dict. Structural `TypedDict`s (not dataclasses) because params/slots are
//! plain JSON dicts at the FFI boundary — no construct/convert churn.

use std::fmt::Write as _;

use cleverhans_core::registry::{ActionDef, BlockDef, ParamSource, ValueType};

use crate::pascal_ident;

/// Header prepended to every generated module.
const HEADER: &str = "\
# AUTO-GENERATED by cleverhans-codegen — do not edit.
# Regenerate from the Rust action registry (spec §9: one source, three consumers).
";

fn py_str(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn py_type(ty: &ValueType) -> String {
    match ty {
        ValueType::String => "str".to_owned(),
        ValueType::Integer => "int".to_owned(),
        ValueType::Number => "float".to_owned(),
        ValueType::Boolean => "bool".to_owned(),
        ValueType::StringEnum(allowed) => format!(
            "Literal[{}]",
            allowed
                .iter()
                .map(|v| py_str(v))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        ValueType::Json => "Any".to_owned(),
    }
}

fn literal_union(out: &mut String, name: &str, ids: &[String]) {
    if ids.is_empty() {
        let _ = writeln!(out, "{name} = Never");
    } else {
        let _ = writeln!(
            out,
            "{name} = Literal[{}]",
            ids.iter().map(|id| py_str(id)).collect::<Vec<_>>().join(", ")
        );
    }
}

fn push_typed_dict<'a>(
    out: &mut String,
    name: &str,
    doc: &str,
    fields: impl Iterator<Item = (&'a str, String, bool, Option<&'a str>)>,
) {
    let _ = writeln!(out, "\nclass {name}(TypedDict):");
    let _ = writeln!(out, "    \"\"\"{doc}\"\"\"");
    let mut empty = true;
    for (field, ty, required, comment) in fields {
        empty = false;
        let ty = if required {
            ty
        } else {
            format!("NotRequired[{ty}]")
        };
        match comment {
            Some(comment) => {
                let _ = writeln!(out, "    {field}: {ty}  # {comment}");
            }
            None => {
                let _ = writeln!(out, "    {field}: {ty}");
            }
        }
    }
    if empty {
        let _ = writeln!(out, "    pass");
    }
}

/// Renders the full generated Python module for a registry's definitions.
///
/// Definitions are emitted in the given order; pass them ID-sorted (a schema
/// document or `Registry::action_defs()`) for deterministic output.
#[must_use]
pub fn python_module<'a>(
    actions: impl IntoIterator<Item = &'a ActionDef>,
    blocks: impl IntoIterator<Item = &'a BlockDef>,
) -> String {
    let actions: Vec<_> = actions.into_iter().collect();
    let blocks: Vec<_> = blocks.into_iter().collect();
    let mut out = String::from(HEADER);
    let _ = writeln!(&mut out, "from __future__ import annotations");
    let _ = writeln!(&mut out);
    let _ = writeln!(
        &mut out,
        "from typing import Any, Literal, Never, NotRequired, TypedDict"
    );
    let _ = writeln!(&mut out);

    literal_union(
        &mut out,
        "ActionId",
        &actions.iter().map(|a| a.id.clone()).collect::<Vec<_>>(),
    );
    literal_union(
        &mut out,
        "BlockType",
        &blocks
            .iter()
            .map(|b| b.block_type.clone())
            .collect::<Vec<_>>(),
    );

    for block in &blocks {
        push_typed_dict(
            &mut out,
            &format!("{}Slots", pascal_ident(&block.block_type)),
            &format!("Slots of block type `{}`.", block.block_type),
            block
                .slots
                .iter()
                .map(|slot| (slot.name.as_str(), py_type(&slot.ty), slot.required, None)),
        );
    }
    for action in &actions {
        push_typed_dict(
            &mut out,
            &format!("{}Params", pascal_ident(&action.id)),
            &format!("Filled params of `{}`.", action.id),
            action.params.iter().map(|param| {
                let source = match param.source {
                    ParamSource::Context => "source: context",
                    ParamSource::Utterance => "source: utterance",
                };
                (
                    param.name.as_str(),
                    py_type(&param.ty),
                    param.required,
                    Some(source),
                )
            }),
        );
    }

    let _ = writeln!(&mut out, "\nclass ActionMeta(TypedDict):");
    let _ = writeln!(
        &mut out,
        "    \"\"\"Wire-visible metadata of one registered action.\"\"\""
    );
    let _ = writeln!(&mut out, "    block_type: BlockType");
    let _ = writeln!(&mut out, "    mutates: bool");

    let _ = writeln!(&mut out, "\nACTIONS: dict[ActionId, ActionMeta] = {{");
    for action in &actions {
        let _ = writeln!(
            &mut out,
            "    {}: {{\"block_type\": {}, \"mutates\": {}}},",
            py_str(&action.id),
            py_str(&action.block_type),
            if action.mutates { "True" } else { "False" }
        );
    }
    let _ = writeln!(&mut out, "}}");

    out
}

#[cfg(test)]
mod tests {
    use cleverhans_core::registry::{ParamSpec, SlotSpec};

    use super::*;

    fn remove_action() -> ActionDef {
        ActionDef {
            id: "transaction.coBuyer.remove".to_owned(),
            description: "Remove the co-buyer".to_owned(),
            params: vec![
                ParamSpec {
                    name: "transactionId".to_owned(),
                    description: String::new(),
                    ty: ValueType::String,
                    source: ParamSource::Context,
                    required: true,
                },
                ParamSpec {
                    name: "country".to_owned(),
                    description: "ISO code".to_owned(),
                    ty: ValueType::StringEnum(vec!["NO".to_owned(), "DK".to_owned()]),
                    source: ParamSource::Utterance,
                    required: false,
                },
            ],
            block_type: "confirm".to_owned(),
            mutates: true,
            authz_key: "tx".to_owned(),
        }
    }

    fn confirm_block() -> BlockDef {
        BlockDef {
            block_type: "confirm".to_owned(),
            slots: vec![
                SlotSpec {
                    name: "title".to_owned(),
                    ty: ValueType::String,
                    required: true,
                },
                SlotSpec {
                    name: "detail".to_owned(),
                    ty: ValueType::String,
                    required: false,
                },
            ],
        }
    }

    #[test]
    fn emits_action_id_literal() {
        let module = python_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("ActionId = Literal[\"transaction.coBuyer.remove\"]"),
            "missing literal union in:\n{module}"
        );
    }

    #[test]
    fn optional_param_gets_not_required() {
        let module = python_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("country: NotRequired[Literal[\"NO\", \"DK\"]]"),
            "missing optional enum param in:\n{module}"
        );
    }

    #[test]
    fn context_param_is_annotated() {
        let module = python_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("transactionId: str  # source: context"),
            "missing context param in:\n{module}"
        );
    }

    #[test]
    fn actions_dict_carries_block_type_and_mutates() {
        let module = python_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains(
                "\"transaction.coBuyer.remove\": {\"block_type\": \"confirm\", \"mutates\": True},"
            ),
            "missing metadata entry in:\n{module}"
        );
    }

    #[test]
    fn empty_registry_yields_never() {
        let module = python_module([], []);

        assert!(
            module.contains("ActionId = Never") && module.contains("BlockType = Never"),
            "empty unions should be Never:\n{module}"
        );
    }

    #[test]
    fn slots_typed_dict_matches_block_schema() {
        let module = python_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("class ConfirmSlots(TypedDict):"),
            "missing slots TypedDict in:\n{module}"
        );
        assert!(
            module.contains("    title: str\n    detail: NotRequired[str]"),
            "missing slot fields in:\n{module}"
        );
    }
}
