//! Rust emitter.
//!
//! Emitted per registry:
//!
//! - `action_ids` / `block_types` constant modules — so app code names
//!   actions through identifiers the compiler checks, not string literals
//! - one params struct per action (context- and utterance-sourced both:
//!   handlers receive *filled* params), deserializable from the validated
//!   [`JsonMap`](cleverhans_core::JsonMap) via
//!   `cleverhans_core::seams::typed_handler`
//! - one enum per string-enum param (closed vocabularies stay closed)
//!
//! The output is a plain module file: write it to `src/generated.rs`, add
//! `pub mod generated;`, and keep it fresh with a golden test comparing
//! [`rust_module`] output against `include_str!`.

use std::fmt::Write as _;

use cleverhans_core::registry::{ActionDef, BlockDef, ParamSource, ParamSpec, ValueType};

use crate::pascal_ident;

/// Header prepended to every generated module.
const HEADER: &str = "\
//! AUTO-GENERATED by cleverhans-codegen — do not edit.
//! Regenerate from the registry document (spec §9: one source, three consumers).
";

/// Converts an inert key like `documents.deleteByStatus` into a constant
/// identifier like `DOCUMENTS_DELETE_BY_STATUS`.
fn const_ident(id: &str) -> String {
    let mut out = String::new();
    for (index, c) in pascal_ident(id).char_indices() {
        if c.is_ascii_uppercase() && index > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

/// Converts a param name like `documentId` into a field identifier like
/// `document_id`.
fn field_ident(name: &str) -> String {
    const_ident(name).to_ascii_lowercase()
}

/// The generated enum name for a string-enum param.
fn param_enum_ident(action: &ActionDef, param: &ParamSpec) -> String {
    format!("{}{}", pascal_ident(&action.id), pascal_ident(&param.name))
}

fn rust_type(action: &ActionDef, param: &ParamSpec) -> String {
    match &param.ty {
        ValueType::String => "String".to_owned(),
        ValueType::Integer => "i64".to_owned(),
        ValueType::Number => "f64".to_owned(),
        ValueType::Boolean => "bool".to_owned(),
        ValueType::StringEnum(_) => param_enum_ident(action, param),
        ValueType::Json => "serde_json::Value".to_owned(),
    }
}

fn push_const_module(out: &mut String, name: &str, doc: &str, ids: &[&str]) {
    let _ = writeln!(out, "\n/// {doc}");
    let _ = writeln!(out, "pub mod {name} {{");
    for id in ids {
        let _ = writeln!(out, "    /// `{id}`");
        let _ = writeln!(out, "    pub const {}: &str = \"{id}\";", const_ident(id));
    }
    let _ = writeln!(out, "}}");
}

fn push_param_enum(out: &mut String, action: &ActionDef, param: &ParamSpec, allowed: &[String]) {
    let _ = writeln!(
        out,
        "\n/// Allowed values of `{}` on `{}`.",
        param.name, action.id
    );
    let _ = writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]"
    );
    let _ = writeln!(out, "pub enum {} {{", param_enum_ident(action, param));
    for value in allowed {
        let _ = writeln!(out, "    #[serde(rename = \"{value}\")]");
        let _ = writeln!(out, "    {},", pascal_ident(value));
    }
    let _ = writeln!(out, "}}");
}

fn push_params_struct(out: &mut String, action: &ActionDef) {
    let _ = writeln!(
        out,
        "\n/// Filled params of `{}`; deserialize the validated map with \
         `cleverhans_core::seams::typed_handler`.",
        action.id
    );
    let _ = writeln!(
        out,
        "#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]"
    );
    let _ = writeln!(out, "#[serde(deny_unknown_fields)]");
    let _ = writeln!(out, "pub struct {}Params {{", pascal_ident(&action.id));
    for param in &action.params {
        let source = match param.source {
            ParamSource::Context => "context",
            ParamSource::Utterance => "utterance",
        };
        let _ = writeln!(out, "    /// source: {source}");
        let field = field_ident(&param.name);
        if field != param.name {
            let _ = writeln!(out, "    #[serde(rename = \"{}\")]", param.name);
        }
        let ty = rust_type(action, param);
        if param.required {
            let _ = writeln!(out, "    pub {field}: {ty},");
        } else {
            let _ = writeln!(
                out,
                "    #[serde(default, skip_serializing_if = \"Option::is_none\")]"
            );
            let _ = writeln!(out, "    pub {field}: Option<{ty}>,");
        }
    }
    let _ = writeln!(out, "}}");
}

/// Renders the full generated Rust module for a registry's definitions.
///
/// Definitions are emitted in the given order; pass them straight from
/// `Registry::action_defs()` / `Registry::block_defs()` (or an ID-sorted
/// schema document) for deterministic output.
#[must_use]
pub fn rust_module<'a>(
    actions: impl IntoIterator<Item = &'a ActionDef>,
    blocks: impl IntoIterator<Item = &'a BlockDef>,
) -> String {
    let actions: Vec<_> = actions.into_iter().collect();
    let blocks: Vec<_> = blocks.into_iter().collect();
    let mut out = String::from(HEADER);

    let action_ids: Vec<&str> = actions.iter().map(|a| a.id.as_str()).collect();
    push_const_module(
        &mut out,
        "action_ids",
        "Action IDs of the registry, for `RegistryBuilder::attach`.",
        &action_ids,
    );
    let block_types: Vec<&str> = blocks.iter().map(|b| b.block_type.as_str()).collect();
    push_const_module(
        &mut out,
        "block_types",
        "Block types of the registry.",
        &block_types,
    );

    for action in &actions {
        for param in &action.params {
            if let ValueType::StringEnum(allowed) = &param.ty {
                push_param_enum(&mut out, action, param, allowed);
            }
        }
        push_params_struct(&mut out, action);
    }

    out
}

#[cfg(test)]
mod tests {
    use cleverhans_core::registry::SlotSpec;

    use super::*;

    fn remove_action() -> ActionDef {
        ActionDef {
            id: "transaction.coBuyer.remove".to_owned(),
            description: "Remove the co-buyer".to_owned(),
            params: vec![
                ParamSpec {
                    name: "transactionId".to_owned(),
                    description: String::new(),
                    ty: ValueType::String,
                    source: ParamSource::Context,
                    required: true,
                },
                ParamSpec {
                    name: "country".to_owned(),
                    description: "ISO code".to_owned(),
                    ty: ValueType::StringEnum(vec!["NO".to_owned(), "DK".to_owned()]),
                    source: ParamSource::Utterance,
                    required: false,
                },
            ],
            block_type: "confirm".to_owned(),
            mutates: true,
            authz_key: "tx".to_owned(),
            display: None,
        }
    }

    fn confirm_block() -> BlockDef {
        BlockDef {
            block_type: "confirm".to_owned(),
            slots: vec![SlotSpec {
                name: "title".to_owned(),
                ty: ValueType::String,
                required: true,
            }],
        }
    }

    #[test]
    fn emits_screaming_snake_action_id_constant() {
        let module = rust_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains(
                "pub const TRANSACTION_CO_BUYER_REMOVE: &str = \"transaction.coBuyer.remove\";"
            ),
            "missing action id constant in:\n{module}"
        );
    }

    #[test]
    fn emits_block_type_constant() {
        let module = rust_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("pub const CONFIRM: &str = \"confirm\";"),
            "missing block type constant in:\n{module}"
        );
    }

    #[test]
    fn camel_case_param_gets_snake_field_with_serde_rename() {
        let module = rust_module([&remove_action()], [&confirm_block()]);

        assert!(
            module
                .contains("#[serde(rename = \"transactionId\")]\n    pub transaction_id: String,"),
            "missing renamed field in:\n{module}"
        );
    }

    #[test]
    fn optional_string_enum_param_becomes_option_of_generated_enum() {
        let module = rust_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("pub country: Option<TransactionCoBuyerRemoveCountry>,"),
            "missing optional enum field in:\n{module}"
        );
        assert!(
            module.contains("pub enum TransactionCoBuyerRemoveCountry {"),
            "missing generated enum in:\n{module}"
        );
        assert!(
            module.contains("#[serde(rename = \"NO\")]\n    No,"),
            "missing renamed variant in:\n{module}"
        );
    }

    #[test]
    fn params_struct_rejects_unknown_fields() {
        let module = rust_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains(
                "#[serde(deny_unknown_fields)]\npub struct TransactionCoBuyerRemoveParams {"
            ),
            "missing deny_unknown_fields in:\n{module}"
        );
    }
}
