//! TypeScript emitter.
//!
//! Emitted per registry:
//!
//! - `ActionId` / `BlockType` string-literal unions (the closed vocabularies)
//! - one params interface per action (context- and utterance-sourced both:
//!   the frontend receives *filled* params in proposals)
//! - one slots interface per block type
//! - `ActionParamsMap` / `BlockSlotsMap` lookup interfaces keyed by ID
//! - an `ACTIONS` metadata const (`blockType`, `mutates`) for the block
//!   router and UI affordances

use std::fmt::Write as _;

use cleverhans_core::registry::{ActionDef, BlockDef, ParamSource, ValueType};

use crate::pascal_ident;

/// Header prepended to every generated module.
const HEADER: &str = "\
// AUTO-GENERATED by cleverhans-codegen — do not edit.
// Regenerate from the Rust action registry (spec §9: one source, three consumers).
";

fn ts_type(ty: &ValueType) -> String {
    match ty {
        ValueType::String => "string".to_owned(),
        ValueType::Integer | ValueType::Number => "number".to_owned(),
        ValueType::Boolean => "boolean".to_owned(),
        ValueType::StringEnum(allowed) => allowed
            .iter()
            .map(|value| format!("\"{}\"", value.replace('"', "\\\"")))
            .collect::<Vec<_>>()
            .join(" | "),
        ValueType::Json => "unknown".to_owned(),
    }
}

fn union_of(ids: impl Iterator<Item = String>) -> String {
    let variants: Vec<_> = ids.map(|id| format!("\"{id}\"")).collect();
    if variants.is_empty() {
        "never".to_owned()
    } else {
        variants.join(" | ")
    }
}

fn push_params_interface(out: &mut String, action: &ActionDef) {
    let name = pascal_ident(&action.id);
    let _ = writeln!(out, "/** Filled params of `{}`. */", action.id);
    let _ = writeln!(out, "export interface {name}Params {{");
    for param in &action.params {
        let source = match param.source {
            ParamSource::Context => "context",
            ParamSource::Utterance => "utterance",
        };
        let optional = if param.required { "" } else { "?" };
        let _ = writeln!(
            out,
            "  /** source: {source} */\n  {}{optional}: {};",
            param.name,
            ts_type(&param.ty)
        );
    }
    let _ = writeln!(out, "}}");
}

fn push_slots_interface(out: &mut String, block: &BlockDef) {
    let name = pascal_ident(&block.block_type);
    let _ = writeln!(out, "/** Slots of block type `{}`. */", block.block_type);
    let _ = writeln!(out, "export interface {name}Slots {{");
    for slot in &block.slots {
        let optional = if slot.required { "" } else { "?" };
        let _ = writeln!(out, "  {}{optional}: {};", slot.name, ts_type(&slot.ty));
    }
    let _ = writeln!(out, "}}");
}

/// Renders the full generated TypeScript module for a registry's definitions.
///
/// Definitions are emitted in the given order; pass them straight from
/// `Registry::action_defs()` / `Registry::block_defs()` (or an ID-sorted
/// schema document) for deterministic output.
#[must_use]
pub fn typescript_module<'a>(
    actions: impl IntoIterator<Item = &'a ActionDef>,
    blocks: impl IntoIterator<Item = &'a BlockDef>,
) -> String {
    let actions: Vec<_> = actions.into_iter().collect();
    let blocks: Vec<_> = blocks.into_iter().collect();
    let mut out = String::from(HEADER);

    let _ = writeln!(
        &mut out,
        "\nexport type ActionId = {};",
        union_of(actions.iter().map(|a| a.id.clone()))
    );
    let _ = writeln!(
        &mut out,
        "\nexport type BlockType = {};",
        union_of(blocks.iter().map(|b| b.block_type.clone()))
    );

    for block in &blocks {
        let _ = writeln!(&mut out);
        push_slots_interface(&mut out, block);
    }
    for action in &actions {
        let _ = writeln!(&mut out);
        push_params_interface(&mut out, action);
    }

    let _ = writeln!(&mut out, "\nexport interface BlockSlotsMap {{");
    for block in &blocks {
        let _ = writeln!(
            &mut out,
            "  \"{}\": {}Slots;",
            block.block_type,
            pascal_ident(&block.block_type)
        );
    }
    let _ = writeln!(&mut out, "}}");

    let _ = writeln!(&mut out, "\nexport interface ActionParamsMap {{");
    for action in &actions {
        let _ = writeln!(
            &mut out,
            "  \"{}\": {}Params;",
            action.id,
            pascal_ident(&action.id)
        );
    }
    let _ = writeln!(&mut out, "}}");

    let _ = writeln!(
        &mut out,
        "\nexport const ACTIONS: {{\n  [K in ActionId]: {{ blockType: BlockType; mutates: boolean }};\n}} = {{"
    );
    for action in &actions {
        let _ = writeln!(
            &mut out,
            "  \"{}\": {{ blockType: \"{}\", mutates: {} }},",
            action.id, action.block_type, action.mutates
        );
    }
    let _ = writeln!(&mut out, "}};");

    out
}

#[cfg(test)]
mod tests {
    use cleverhans_core::registry::{ParamSpec, SlotSpec};

    use super::*;

    fn remove_action() -> ActionDef {
        ActionDef {
            id: "transaction.coBuyer.remove".to_owned(),
            description: "Remove the co-buyer".to_owned(),
            params: vec![
                ParamSpec {
                    name: "transactionId".to_owned(),
                    description: String::new(),
                    ty: ValueType::String,
                    source: ParamSource::Context,
                    required: true,
                },
                ParamSpec {
                    name: "country".to_owned(),
                    description: "ISO code".to_owned(),
                    ty: ValueType::StringEnum(vec!["NO".to_owned(), "DK".to_owned()]),
                    source: ParamSource::Utterance,
                    required: false,
                },
            ],
            block_type: "confirm".to_owned(),
            mutates: true,
            authz_key: "tx".to_owned(),
        }
    }

    fn confirm_block() -> BlockDef {
        BlockDef {
            block_type: "confirm".to_owned(),
            slots: vec![
                SlotSpec {
                    name: "title".to_owned(),
                    ty: ValueType::String,
                    required: true,
                },
                SlotSpec {
                    name: "detail".to_owned(),
                    ty: ValueType::String,
                    required: false,
                },
            ],
        }
    }

    #[test]
    fn emits_action_id_union() {
        let module = typescript_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("export type ActionId = \"transaction.coBuyer.remove\";"),
            "missing union in:\n{module}"
        );
    }

    #[test]
    fn optional_param_gets_question_mark() {
        let module = typescript_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("country?: \"NO\" | \"DK\";"),
            "missing optional enum param in:\n{module}"
        );
    }

    #[test]
    fn required_context_param_is_plain_string() {
        let module = typescript_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains("transactionId: string;"),
            "missing context param in:\n{module}"
        );
    }

    #[test]
    fn metadata_const_carries_block_type_and_mutates() {
        let module = typescript_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains(
                "\"transaction.coBuyer.remove\": { blockType: \"confirm\", mutates: true },"
            ),
            "missing metadata entry in:\n{module}"
        );
    }

    #[test]
    fn empty_registry_yields_never_unions() {
        let module = typescript_module([], []);

        assert!(
            module.contains("export type ActionId = never;"),
            "empty union should be never:\n{module}"
        );
    }

    #[test]
    fn slots_interface_matches_block_schema() {
        let module = typescript_module([&remove_action()], [&confirm_block()]);

        assert!(
            module.contains(
                "export interface ConfirmSlots {\n  title: string;\n  detail?: string;\n}"
            ),
            "missing slots interface in:\n{module}"
        );
    }
}
