//! AUTO-GENERATED by cleverhans-codegen — do not edit.
//! Regenerate from the registry document (spec §9: one source, three consumers).

/// Action IDs of the registry, for `RegistryBuilder::attach`.
pub mod action_ids {
    /// `document.archive`
    pub const DOCUMENT_ARCHIVE: &str = "document.archive";
    /// `document.publish`
    pub const DOCUMENT_PUBLISH: &str = "document.publish";
    /// `document.rename`
    pub const DOCUMENT_RENAME: &str = "document.rename";
    /// `documents.deleteByStatus`
    pub const DOCUMENTS_DELETE_BY_STATUS: &str = "documents.deleteByStatus";
}

/// Block types of the registry.
pub mod block_types {
    /// `bulk_preview`
    pub const BULK_PREVIEW: &str = "bulk_preview";
    /// `confirm`
    pub const CONFIRM: &str = "confirm";
}

/// Filled params of `document.archive`; deserialize the validated map with `cleverhans_core::seams::typed_handler`.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DocumentArchiveParams {
    /// source: context
    #[serde(rename = "documentId")]
    pub document_id: String,
}

/// Filled params of `document.publish`; deserialize the validated map with `cleverhans_core::seams::typed_handler`.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DocumentPublishParams {
    /// source: context
    #[serde(rename = "documentId")]
    pub document_id: String,
}

/// Filled params of `document.rename`; deserialize the validated map with `cleverhans_core::seams::typed_handler`.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DocumentRenameParams {
    /// source: context
    #[serde(rename = "documentId")]
    pub document_id: String,
    /// source: utterance
    pub title: String,
}

/// Allowed values of `status` on `documents.deleteByStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum DocumentsDeleteByStatusStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "published")]
    Published,
    #[serde(rename = "archived")]
    Archived,
}

/// Filled params of `documents.deleteByStatus`; deserialize the validated map with `cleverhans_core::seams::typed_handler`.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DocumentsDeleteByStatusParams {
    /// source: utterance
    pub status: DocumentsDeleteByStatusStatus,
}
