/**
 * `@cleverhans/node` — host a CleverHans propose-only agent from a Node.js
 * backend. The agent never acts on your system: it proposes actions from
 * your closed registry; your handlers execute only after explicit user
 * confirmation, under the principal you bound to the session.
 *
 * This wrapper owns the ergonomic surface over the napi binding: it
 * normalizes registry/config inputs, guarantees callbacks are async (sync
 * throws become rejections), and maps the {@link Rejected} class onto the
 * binding's rejection sentinel. WebSocket glue stays in your app — see
 * `examples/node-demo`.
 */

import { readFileSync } from "node:fs";

// Generated by `napi build --platform` (package-root loader + .d.ts).
// eslint-disable-next-line @typescript-eslint/no-require-imports
import {
  Agent as NativeAgent,
  Session as NativeSession,
  generateTypes as nativeGenerateTypes,
} from "../index.js";

/** JSON-compatible value. */
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

/** Filled params / slots / identity blobs. */
export type JsonObject = Record<string, Json>;

/** An action handler: the app's normal execution path (spec §9.2). */
export type Handler = (params: JsonObject, principal: JsonObject) => unknown | Promise<unknown>;

/** Authorization: `null`/`true` allow, string denies with reason (§9.3). */
export type Authorize = (
  principal: JsonObject,
  actionId: string,
  params: JsonObject,
) => null | boolean | string | Promise<null | boolean | string>;

/** Declarative slot content: slot name → value source (spec §9.7). */
export type SlotTable = Record<
  string,
  { const: Json } | { param: string } | { preview: "summary" }
>;

/** Built-in provider spec, or a custom completion callback. */
export type LlmOption =
  | { provider: "anthropic"; api_key: string; model?: string }
  | { provider: "ollama"; model: string; base_url?: string }
  | { provider: "scripted"; script: unknown[][] }
  | ((request: JsonObject) => unknown | Promise<unknown>);

/** Agent construction options. */
export interface AgentOptions {
  /** Registry document: path, JSON string, or object (spec §4). */
  registry: string | JsonObject;
  /** One handler per action ID; must cover every action. */
  handlers: Record<string, Handler>;
  /** One dry-run per mutating action ID (spec §7.2). */
  dryRuns?: Record<string, Handler>;
  /** Declarative slot content per action ID. */
  slotBuilders?: Record<string, SlotTable>;
  /** Authorization resolver; omit to allow everything (dev only). */
  authorize?: Authorize;
  /** LLM provider. */
  llm: LlmOption;
  /** Loop configuration. */
  config?: {
    app_instructions?: string;
    max_validation_retries?: number;
    describe_context?: boolean;
  };
}

/** A server event as delivered to `onEvent` (parsed envelope JSON). */
export type ServerEvent = JsonObject & { type: string };

/**
 * Raise from a handler or dry-run to decline as a business rule: the
 * proposal reports `failed` with this message as the reason (subclasses
 * count — the mapping is `instanceof`-based). Any other throw maps to an
 * internal error.
 */
export class Rejected extends Error {}

// Every callback result crosses the boundary in a total envelope, so a
// legitimate handler result can never collide with the rejection marker.
const OK_KEY = "__cleverhans_ok";
const REJECTED_KEY = "__cleverhans_rejected";

function wrapHandler(fn: Handler): (a: JsonObject, b: JsonObject) => Promise<unknown> {
  return async (params, principal) => {
    try {
      return { [OK_KEY]: await fn(params, principal) };
    } catch (err) {
      if (err instanceof Rejected) {
        return { [REJECTED_KEY]: err.message };
      }
      throw err;
    }
  };
}

function registryJson(registry: string | JsonObject): string {
  if (typeof registry !== "string") {
    return JSON.stringify(registry);
  }
  if (registry.trimStart().startsWith("{")) {
    return registry;
  }
  return readFileSync(registry, "utf8");
}

function mapValues<T, U>(map: Record<string, T> | undefined, fn: (value: T) => U): Record<string, U> {
  return Object.fromEntries(Object.entries(map ?? {}).map(([key, value]) => [key, fn(value)]));
}

/** One envelope session, bound to one principal. */
export class Session {
  #native: NativeSession;
  /** Serializes turns so `onEvent` callbacks never interleave. */
  #queue: Promise<unknown> = Promise.resolve();

  constructor(native: NativeSession) {
    this.#native = native;
  }

  /**
   * True after an init-first violation closed the session (spec §6.1).
   * Further frames emit no events; close your transport.
   */
  get closed(): boolean {
    return this.#native.closed;
  }

  /**
   * Handles one client event (JSON string or object); `onEvent` fires per
   * server event as it becomes available. Resolves when the turn
   * completes, with `true` when the session is closed (spec §6.1) — close
   * your transport then.
   */
  handle(frame: string | JsonObject, onEvent: (event: ServerEvent) => void): Promise<boolean> {
    const raw = typeof frame === "string" ? frame : JSON.stringify(frame);
    const turn = this.#queue.then(() =>
      this.#native.handle(raw, (json: string) => {
        onEvent(JSON.parse(json) as ServerEvent);
      }),
    );
    this.#queue = turn.catch(() => undefined);
    return turn;
  }

  /** Like {@link handle}, collecting the whole turn into an array. */
  async handleCollect(frame: string | JsonObject): Promise<ServerEvent[]> {
    const events: ServerEvent[] = [];
    await this.handle(frame, (event) => events.push(event));
    return events;
  }
}

/**
 * The propose-only agent over your registry and seams. Stateless and
 * shared: open one {@link Session} per authenticated stream. Protocol
 * failures surface as `error` events on the stream, never as exceptions;
 * only construction errors throw.
 */
export class Agent {
  #native: NativeAgent;

  constructor(options: AgentOptions) {
    const llmSpec = typeof options.llm === "function" ? null : JSON.stringify(options.llm);
    const llmCallable =
      typeof options.llm === "function"
        ? wrapHandler(options.llm as unknown as Handler)
        : null;
    const authorize = options.authorize
      ? async (principal: JsonObject, actionId: string, params: JsonObject) => {
          try {
            return await options.authorize!(principal, actionId, params);
          } catch (err) {
            return `authorize raised: ${err instanceof Error ? err.message : String(err)}`;
          }
        }
      : null;
    this.#native = new NativeAgent(
      registryJson(options.registry),
      mapValues(options.handlers, wrapHandler),
      mapValues(options.dryRuns, wrapHandler),
      (options.slotBuilders ?? {}) as Record<string, Json>,
      authorize,
      llmSpec,
      llmCallable,
      options.config ? JSON.stringify(options.config) : null,
    );
  }

  /** Opens a session as the authenticated principal (a JSON identity blob —
   * live resources belong in handler closures). */
  session(principal: JsonObject): Session {
    return new Session(this.#native.session(principal));
  }
}

/**
 * The slice of a WebSocket the agent needs — satisfied by `ws`, `uWS`, and
 * anything socket-shaped, so the adapter stays framework-neutral.
 */
export interface AgentSocket {
  send(data: string): void;
  close(): void;
}

/**
 * Bridges one authenticated socket to one agent session: returns the message
 * listener that pumps frames through the session and mirrors the Rust WS
 * binding's close-on-init-violation. The only glue left in your app is
 * wiring it to your server's connection event:
 *
 * ```ts
 * wss.on("connection", (ws, request) => {
 *   const principal = authenticate(request); // your auth, before any frame
 *   ws.on("message", bindAgentSocket(agent, principal, ws));
 * });
 * ```
 */
export function bindAgentSocket(
  agent: Agent,
  principal: JsonObject,
  socket: AgentSocket,
): (data: unknown) => void {
  const session = agent.session(principal);
  return (data) => {
    void session
      .handle(String(data), (event) => socket.send(JSON.stringify(event)))
      .then((closed) => {
        // Init-first violation (spec §6.1): close instead of leaving a
        // zombie stream.
        if (closed) {
          socket.close();
        }
      });
  };
}

/** A codegen output language. */
export type CodegenTarget = "typescript" | "python" | "rust";

/**
 * Generates a typed module from a registry document (path, JSON string, or
 * object) — the registry codegen without a Rust toolchain. Wire it into your
 * build (`npx cleverhans-codegen` fronts the same call) so action IDs and
 * params stay typed as the registry evolves.
 */
export function generateTypes(
  registry: string | JsonObject,
  target: CodegenTarget = "typescript",
): string {
  return nativeGenerateTypes(registryJson(registry), target);
}
